### ISSUE TITLE
Specifying a type to use for parameter-less "static" default methods in a trait

### ISSUE THREAD

**Issue by SimonSapin** [servo/rust-core-foundation#17]
`<T>` in this line is no longer valid in Rust master:
https://github.com/mozilla-servo/rust-core-foundation/blob/1f43d00330/base.rs#L57

Having a dummy parameter of type `Option<Self>` could work, but refactoring across repositories this will be a pain. (Not to mention how ugly it is.)

**Comment by zummenix** [comment]
Now this is possible to remove dummy parameter in `type_id` function:
```rust
fn type_id(dummy: Option<Self>) -> CFTypeID;
```
I was thinking about deprecation of this function and adding new one but I can't to come up with new name.

**Comment by SimonSapin** [comment]
I don’t think we’re making any API stability promises for this library. Feel free to just remove the dummy parameter. If you also want to patch Servo and related libraries to use this change, that’d be great!
